### ISSUE TITLE
Conflict with other libraries when loaded through script tag

### ISSUE THREAD

**Issue by thekiba** [lordicondev/lordicon#1]
**Describe the bug**
When the lordicon library is loaded through a script tag in HTML, it to cause conflicts with other libraries or scripts included on the page. The issue due to the fact that lordicon is not built in a format such as UMD.

**To Reproduce**
1. Create an HTML file and include the lordicon library using a script tag.
2. Include another library or script on the page.
3. Observe any conflicts or issues that arise.

**Expected behavior**
The lordicon library should not cause conflicts with other scripts or libraries included on the page.

**Screenshots**
See this issue for more details and a user report: [https://github.com/ton-connect/sdk/issues/99](https://github.com/ton-connect/sdk/issues/99).

**Additional context**
I recommend re-building the lordicon library in a format as UMD, to ensure compatibility with other scripts or libraries on the page.

**Comment by baszczewski** [comment]
We don't need the UMD module format here because, in this usage example, we don't import anything from another script. The problem lies in the unnecessary global variable declarations.

Thank you for the report.

**Comment by baszczewski** [comment]
There is an update for the released version of the library (IIFE output format used for Rollup):
https://cdn.lordicon.com/lordicon-1.2.0.js
