### ISSUE TITLE
Error `Illegal constructor` CSSStyleSheet

### ISSUE THREAD

**Issue by vuthanhbayit** [lordicondev/lordicon#11]
**Describe the bug**
Hello, I am using Lordicon on iOS Safari, in my project and website lordicon.com as follows:

![image](https://github.com/user-attachments/assets/0395a3bf-2fe5-440c-be7d-3887af6e7175)

**To Reproduce**
1. Go to lordicon.com by iphone IOS 16 safari

**Comment by vuthanhbayit** [comment]
https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes#CSS-API

From version 16.4 or less, not supported by Support CSS API

**Comment by baszczewski** [comment]
Thank you for your report. That's correct. Our library uses a feature that has been available in Safari for over a year. Why not consider updating your browser in this case?
If support for older browsers is crucial for you, you can:

- Use an older version of the library that didn't require this functionality in browsers (though this solution might not work well with the new icons we provide).
- Integrate lottie-web directly into your project.

**Comment by vuthanhbayit** [comment]
> Thank you for your report. That's correct. Our library uses a feature that has been available in Safari for over a year. Why not consider updating your browser in this case? If support for older browsers is crucial for you, you can:
> 
> * Use an older version of the library that didn't require this functionality in browsers (though this solution might not work well with the new icons we provide).
> * Integrate lottie-web directly into your project.

Thanks for reply:

1. I can't ask our users to use a newer version of iOS, we need to support all customers.
2. I bought Lord-icon's Pro package and now used Lottie-Web :D
![image](https://github.com/user-attachments/assets/f2c4a231-a5ba-470c-a1e6-cb576bb0316f)

I think just one piece of Code update Support CSS API, can I help, what do you think?

**Comment by baszczewski** [comment]
Support for this missing feature in Safari is simple to implement by using an alternative method of loading CSS. We have done this in the past until the feature became widely available on updated devices on the market. I don't have an opinion on whether we should reinstate the old solution in the current version of the library or for how long.

---
Our legacy solution with SUPPORTS_ADOPTING_STYLE_SHEETS:

https://github.com/lordicondev/lordicon/blob/c7ce72ed2db95c7f64e610f9028864f624e7e91d/packages/element/src/element.ts

**Comment by vuthanhbayit** [comment]
> Support for this missing feature in Safari is simple to implement by using an alternative method of loading CSS. We have done this in the past until the feature became widely available on updated devices on the market. I don't have an opinion on whether we should reinstate the old solution in the current version of the library or for how long.
> 
> Our legacy solution with SUPPORTS_ADOPTING_STYLE_SHEETS:
> 
> https://github.com/lordicondev/lordicon/blob/c7ce72ed2db95c7f64e610f9028864f624e7e91d/packages/element/src/element.ts

Thank you for the detailed information on SUPPORTS_ADOPTING_STYLE_SHEETS. I understand that this feature is now available on many updated devices, but we truly need to support users on older iOS devices as well. Requiring our customers to update their devices isn’t always feasible, especially when supporting those who may not be able or willing to upgrade their iOS version.

We purchased the Lordicon Pro package because we love the quality and versatility of your icons. Restoring SUPPORTS_ADOPTING_STYLE_SHEETS in the library would help us continue providing a consistent, high-quality experience for all our users, regardless of device limitations. Would it be possible to consider a version update that reinstates this feature?

This approach would add significant value for all customers in similar situations. Thank you very much for considering this!

**Comment by baszczewski** [comment]
Ready along with version 1.10.1.

**Comment by vuthanhbayit** [comment]
> Ready along with version 1.10.1.

Thank you so much for your quick response and for implementing this feature! We truly appreciate your support and dedication to improving compatibility. Thanks again!

**Comment by monkeykingblack** [comment]
> Ready along with version 1.10.1.

Thank you for your work on the issue. However, the issue is only resolved in the `@lordicon/element` package. It is still present in the `@lordicon/react` package. I hope the implementation will work for both.
