### ISSUE TITLE
Next.js Support

### ISSUE THREAD

**Issue by dclstn** [lordicondev/lordicon#2]
**Describe the bug**
Player.tsx cannot be rendered server-side

**To Reproduce**
1. Create a Next.js Project
2. Use `<Player />`

**Expected behavior**
Player should fallback to some image

**Screenshots**
```
 ⨯ ../node_modules/@lordicon/react/dist/player.js (1:294) @ Document
 ⨯ ReferenceError: Document is not defined
```

**Comment by airplaneboy** [comment]
You can use the [react lordicon](https://www.npmjs.com/package/@lordicon/react) package. but if you prefer this for what ever reason, I can try to guide you through since I also faced those issues and I found workarounds

**Comment by dclstn** [comment]
React lordicon is the library I'm having issues with

**Comment by airplaneboy** [comment]
Have you solve it? Because I have a work around for that too. Here's my code.

```//LordIconPlayer.tsx
// ../components/LordIconPlayer.tsx
'use client';
import { Player } from '@lordicon/react';
import { useRef } from 'react';

const LordIconPlayer = ({
  src,
  size = 96,
  className,
}: {
  src: string;
  size?: number;
  className?: string | undefined;
}) => {
  const playerRef = useRef<Player>(null);

  const onHover = () => playerRef.current?.play();

  return (
    <div onMouseOver={onHover} className={className + ' w-max h-max'}>
      <Player onComplete={() => playerRef.current?.goToFirstFrame()} size={size} ref={playerRef} icon={src} />
    </div>
  );
};

export default LordIconPlayer;
```

```//LordIcon.tsx
//LordIcon.tsx
import dynamic from 'next/dynamic';

const LordIcon = async ({ src, size, className }: { src: string; size?: number; className?: string | undefined }) => {
  const LordIconPlayer = dynamic(() => import('@/components/LordIconPlayer'), {
    ssr: false,
    loading: () => <span>Loading</span>,
  });

  // const ICON = 'https://cdn.lordicon.com/egmlnyku.json';

  const response = await fetch(src.startsWith('https') ? src : `https://cdn.lordicon.com/${src}.json`);
  const data = await response.json();

  return <LordIconPlayer className={className} src={data} size={size} />;
};
export default LordIcon;

**Comment by dclstn** [comment]
How would this work with `playerRef` ?

**Comment by airplaneboy** [comment]
> How would this work with `playerRef` ?

I don’t understand your question, but `playerRef` allows you to access the instance methods on `Player`. But you really don’t have to worry about that. 
**For Usage:**
- Create a file called `LordIconPlayer.tsx` in your components folder (or literally anywhere)
- Also, create another file called `LordIcon.tsx` anywhere 
- Now, starting from the comments in the code above showing the file names, copy and paste each code to its respective file.
- Finally, go to where you want to use the animated icon and import the `LordIcon` component.
- Then, use the component (assuming you imported it as “LordIcon” like this 

```//example
<LordIcon src={/*The link to the animated icon for example 'https://cdn.lordicon.com/egmlnyku.json' */} className={/*Use this to apply styles*/} size={/*Use this prop to specify the size of the icon*/}/>
```

 anywhere you want

**Comment by dclstn** [comment]
I specifically need to use `ref`, you should try using ref.

**Comment by airplaneboy** [comment]
> I specifically need to use `ref`, you should try using ref.

I’m using ref in that code. look at this part 
 ``` //here
<Player onComplete={() => playerRef.current?.goToFirstFrame()} size={size} ref={playerRef} icon={src} />

**Comment by airplaneboy** [comment]
Hey, did you get it to work?

**Comment by dclstn** [comment]
Yes, thank you. Do you know a way I can render a static fallback of the Lordicon. rather than rendering `<span>Loading</span>`

**Comment by dclstn** [comment]
```js
'use client';

import React from 'react';
import useLazy from '@/hooks/useLazy';
import {LordIconProps} from '@/types/client';
import dynamic from 'next/dynamic';
import {Icon} from '@chakra-ui/react';

function StaticHomeIcon(props: React.ComponentProps<typeof Icon>) {
  return (
    <Icon viewBox="0 0 500 500" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}>
      <mask id="mask0_1_3" maskUnits="userSpaceOnUse" x="0" y="0" width="500" height="500">
        <path d="M0 0H500V500H0V0Z" fill="white" />
      </mask>
      <g mask="url(#mask0_1_3)">
        <path d="M419.617 171.471L273.807 70.008C259.559 60.093 240.437 60.093 226.189 70.008L80.38 171.471C74.8695 175.313 70.3688 180.429 67.2607 186.384C64.1527 192.339 62.5294 198.957 62.529 205.674V395.81C62.529 418.786 81.214 437.47 104.189 437.47H145.537C179.989 437.47 208.027 409.433 208.027 374.98L208.006 291.619H291.971L291.992 374.98C291.992 409.433 320.029 437.47 354.482 437.47H395.809C418.784 437.47 437.469 418.786 437.469 395.81V205.674C437.469 198.957 435.845 192.339 432.737 186.384C429.629 180.429 425.128 175.313 419.618 171.471H419.617Z" />
      </g>
    </Icon>
  );
}

export default function Home({size, ...props}: Omit<LordIconProps, 'icon'>) {
  const data = useLazy(async () => (await import('./home.json')).default);

  const LordIconPlayer = dynamic(() => import('@/components/LordIconPlayer'), {
    ssr: false,
    loading: () => <StaticHomeIcon width={`${size}px`} height={`${size}px`} />,
  });

  return <LordIconPlayer icon={data} size={size} {...props} />;
}
```

I got it, thank you for your help. LordIcon provides static versions of their icons thankfully.

**Comment by Danieldo1** [comment]
> ```tsx
> 'use client';
> import { Player } from '@lordicon/react';
> import { useRef } from 'react';
> 
> const LordIconPlayer = ({
>   src,
>   size = 96,
>   className,
> }: {
>   src: string;
>   size?: number;
>   className?: string | undefined;
> }) => {
>   const playerRef = useRef<Player>(null);
> 
>   const onHover = () => playerRef.current?.play();
> 
>   return (
>     <div onMouseOver={onHover} className={className + ' w-max h-max'}>
>       <Player onComplete={() => playerRef.current?.goToFirstFrame()} size={size} ref={playerRef} icon={src} />
>     </div>
>   );
> };
> 
> export default LordIconPlayer;
> ```

for some reason i get this following error
Error: async/await is not yet supported in Client Components, only Server Components. This error is often caused by accidentally adding `'use client'` to a module that was originally written for the server.
I have followed your instructions and calling the image correctly

**Comment by dclstn** [comment]
```js
'use client';

import React from 'react';
import useLazy from '@/hooks/useLazy';
import {LordIconProps} from '@/types/client';
import dynamic from 'next/dynamic';
import {Icon} from '@chakra-ui/react';

function StaticAlarmIcon(props: React.ComponentProps<typeof Icon>) {
  return (
    <Icon viewBox="0 0 500 500" fill="currentColor" {...props}>
      <path d="M431.314 131.114L368.866 68.707C360.721 60.562 347.556 60.562 339.412 68.707C331.267 76.851 331.267 90.037 339.412 98.16L401.86 160.567C403.792 162.504 406.087 164.04 408.615 165.087C411.142 166.135 413.851 166.673 416.587 166.67C419.323 166.673 422.032 166.135 424.559 165.087C427.086 164.04 429.382 162.504 431.314 160.567C439.459 152.423 439.459 139.237 431.314 131.114Z" />
      <path d="M160.573 68.758C152.429 60.613 139.264 60.613 131.12 68.758L68.755 131.123C60.61 139.246 60.61 152.432 68.755 160.576C70.6868 162.513 72.9821 164.049 75.5092 165.097C78.0363 166.144 80.7454 166.682 83.481 166.68C86.2168 166.682 88.9261 166.145 91.4534 165.097C93.9806 164.05 96.2761 162.513 98.208 160.576L160.573 98.211C168.718 90.088 168.718 76.902 160.573 68.758Z" />
      <path d="M355.606 350.188C409.764 293.114 408.931 202.92 353.106 146.888C325.611 119.392 288.95 104.186 249.998 104.186C211.046 104.186 174.385 119.392 146.89 146.888C91.065 202.92 90.232 293.114 144.39 350.188L107.73 405.18C101.272 414.553 103.98 427.676 113.562 433.925C117.102 436.425 121.06 437.466 125.018 437.466C131.684 437.466 138.349 434.133 142.308 428.093L177.093 376.018C199.59 388.932 224.793 395.598 249.998 395.598C275.202 395.598 300.407 388.932 322.903 376.018L357.689 428.093C361.647 434.133 368.313 437.466 374.979 437.466C378.936 437.466 382.894 436.425 386.435 433.925C396.016 427.676 398.725 414.553 392.267 405.18L355.607 350.188H355.606ZM306.447 306.238C302.49 310.403 297.074 312.486 291.658 312.486C286.451 312.486 281.035 310.403 277.078 306.237L235.208 264.577C233.334 262.702 231.876 260.411 230.835 257.911C230.418 256.87 230.001 256.037 230.001 254.995C229.376 253.329 229.168 251.662 229.168 249.788V208.336C229.168 196.88 238.542 187.506 249.998 187.506C261.455 187.506 270.828 196.88 270.828 208.336V241.039L306.448 276.867C314.571 284.99 314.571 298.113 306.448 306.237L306.447 306.238Z" />
    </Icon>
  );
}

const LoadingContext = React.createContext<{size: number} | null>(null);

const LordIconPlayer = dynamic(() => import('@/components/LordIcon'), {
  ssr: false,
  loading: function Loading() {
    const {size} = React.useContext(LoadingContext) ?? {};
    return <StaticAlarmIcon width={`${size}px`} height={`${size}px`} />;
  },
});

export default function Alarm({size, ...props}: Omit<LordIconProps, 'icon'>) {
  const data = useLazy(async () => (await import('./alarm.json')).default);
  return (
    <LoadingContext.Provider value={{size}}>
      <LordIconPlayer icon={data} size={size} {...props} />
    </LoadingContext.Provider>
  );
}
```

I solved this by using Next's dynamic SSR function @Danieldo1

**Comment by Danieldo1** [comment]
> ```js
> 'use client';
> 
> import React from 'react';
> import useLazy from '@/hooks/useLazy';
> import {LordIconProps} from '@/types/client';
> import dynamic from 'next/dynamic';
> import {Icon} from '@chakra-ui/react';
> 
> function StaticAlarmIcon(props: React.ComponentProps<typeof Icon>) {
>   return (
>     <Icon viewBox="0 0 500 500" fill="currentColor" {...props}>
>       <path d="M431.314 131.114L368.866 68.707C360.721 60.562 347.556 60.562 339.412 68.707C331.267 76.851 331.267 90.037 339.412 98.16L401.86 160.567C403.792 162.504 406.087 164.04 408.615 165.087C411.142 166.135 413.851 166.673 416.587 166.67C419.323 166.673 422.032 166.135 424.559 165.087C427.086 164.04 429.382 162.504 431.314 160.567C439.459 152.423 439.459 139.237 431.314 131.114Z" />
>       <path d="M160.573 68.758C152.429 60.613 139.264 60.613 131.12 68.758L68.755 131.123C60.61 139.246 60.61 152.432 68.755 160.576C70.6868 162.513 72.9821 164.049 75.5092 165.097C78.0363 166.144 80.7454 166.682 83.481 166.68C86.2168 166.682 88.9261 166.145 91.4534 165.097C93.9806 164.05 96.2761 162.513 98.208 160.576L160.573 98.211C168.718 90.088 168.718 76.902 160.573 68.758Z" />
>       <path d="M355.606 350.188C409.764 293.114 408.931 202.92 353.106 146.888C325.611 119.392 288.95 104.186 249.998 104.186C211.046 104.186 174.385 119.392 146.89 146.888C91.065 202.92 90.232 293.114 144.39 350.188L107.73 405.18C101.272 414.553 103.98 427.676 113.562 433.925C117.102 436.425 121.06 437.466 125.018 437.466C131.684 437.466 138.349 434.133 142.308 428.093L177.093 376.018C199.59 388.932 224.793 395.598 249.998 395.598C275.202 395.598 300.407 388.932 322.903 376.018L357.689 428.093C361.647 434.133 368.313 437.466 374.979 437.466C378.936 437.466 382.894 436.425 386.435 433.925C396.016 427.676 398.725 414.553 392.267 405.18L355.607 350.188H355.606ZM306.447 306.238C302.49 310.403 297.074 312.486 291.658 312.486C286.451 312.486 281.035 310.403 277.078 306.237L235.208 264.577C233.334 262.702 231.876 260.411 230.835 257.911C230.418 256.87 230.001 256.037 230.001 254.995C229.376 253.329 229.168 251.662 229.168 249.788V208.336C229.168 196.88 238.542 187.506 249.998 187.506C261.455 187.506 270.828 196.88 270.828 208.336V241.039L306.448 276.867C314.571 284.99 314.571 298.113 306.448 306.237L306.447 306.238Z" />
>     </Icon>
>   );
> }
> 
> const LoadingContext = React.createContext<{size: number} | null>(null);
> 
> const LordIconPlayer = dynamic(() => import('@/components/LordIcon'), {
>   ssr: false,
>   loading: function Loading() {
>     const {size} = React.useContext(LoadingContext) ?? {};
>     return <StaticAlarmIcon width={`${size}px`} height={`${size}px`} />;
>   },
> });
> 
> export default function Alarm({size, ...props}: Omit<LordIconProps, 'icon'>) {
>   const data = useLazy(async () => (await import('./alarm.json')).default);
>   return (
>     <LoadingContext.Provider value={{size}}>
>       <LordIconPlayer icon={data} size={size} {...props} />
>     </LoadingContext.Provider>
>   );
> }
> ```
> 
> I solved this by using Next's dynamic SSR function @Danieldo1

do you have useLazy hook code i try with it and it seems to not run without this hook. thanks

**Comment by airplaneboy** [comment]
> supported

can you share your code. the error you got normally shows up if you're trying to fetch with async await inside of a client component, which isn't allowed in next.js

**Comment by baszczewski** [comment]
I made several minor changes in response to this report. Additionally, I created a repository with an example of integrating our icons with a Next.js project:

https://github.com/lordicondev/demo-nextjs
