### ISSUE TITLE
Support for .lottie File Format for Animations

### ISSUE THREAD

**Issue by JulioFerrero** [lordicondev/lordicon#4]
**Is your feature request related to a problem? Please describe.**

I'm frustrated that I can't use .lottie files for animations in our application. This limitation restricts the use of advanced animation features and optimizations.

**Describe the solution you'd like**

I would like the application to support .lottie files. This format offers advantages like smaller file sizes, improved performance, and the ability to include complex animation data.

**Describe alternatives you've considered**

I considered converting .lottie files to other formats, but this can be cumbersome and may not preserve the benefits of .lottie files. Using third-party plugins is another option, but it adds complexity and potential compatibility issues.

**Additional context**

Supporting .lottie files aligns with industry standards and practices, enhancing user experience and keeping the application competitive with current technological advancements in animation.

**Comment by baszczewski** [comment]
If your application needs to display Lottie animations, you're in the right place. Our prepared library can assist you, especially when paired with icons downloaded from lordicon.com.

PS
Keep in mind that Lottie animations are essentially JSON files. The format we give in the file name doesn't matter.
