### ISSUE TITLE
ES module compatibility for @lordicon/element

### ISSUE THREAD

**Issue by julienchazal** [lordicondev/lordicon#5]
**Is your feature request related to a problem? Please describe.**
When i import `@lordicon/element` inside SvelteKit i get this error :

```bash
 Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
 [vite] Error when evaluating SSR module /src/lib/elements/Icon.svelte: failed to import "@lordicon/element"
 
 ...
 
 SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)


```

**Describe the solution you'd like**
lordicon should be compatible with modern NodeJS features

**Describe alternatives you've considered**

**Additional context**
NodeJS version : 18.15.0
https://kit.svelte.dev/docs/faq#how-do-i-fix-the-error-i-m-getting-trying-to-include-a-package

**Comment by ESoch** [comment]
Hi,

This is an issue for us as well. Is this repository still maintained by LordIcon? This issue has been open since May 31st without response.

This is something which would certainly impact our decision on whether to leverage LordIcon as a solution or not.

**Comment by baszczewski** [comment]
Thank you very much for your submission. We have released an update to the library where the package is of type 'module', so this type of message during import should no longer occur. Additionally, we have prepared a sample mini application that demonstrates how to integrate the custom element with SvelteKit.

https://github.com/lordicondev/demo-sveltekit

**Comment by julienchazal** [comment]
@baszczewski great thanks a lot !
