### ISSUE TITLE
goToLastFrame() not get last image

### ISSUE THREAD

**Issue by DatTN95** [lordicondev/lordicon#6]
hello guys
in the loop it doesn't run all the images
i tried goToLastFrame() but it not get last image
this last image when view normal
![image](https://github.com/lordicondev/lordicon/assets/159091627/aae7ea23-fb61-4639-bb51-73f4249295d7)
but when use @lordicon/react to loop
![image](https://github.com/lordicondev/lordicon/assets/159091627/cd065252-bd79-418c-8fce-807f829f6e54)
 
 my code
 import { NavLink } from 'react-router-dom';
import { routes } from '../../Configures/Routes';
import { useTranslation } from 'react-i18next';
import { useSelector } from 'react-redux';
import { Row, Col, Card } from 'react-bootstrap';
import icError from '../../Assets/Images/Json/error.json';
import { Player } from '@lordicon/react';
import { useEffect, useRef } from 'react';

const Error = () => {
    const { t } = useTranslation();
    const { message } = useSelector(state => state.userInfo);

    const playerRef = useRef(null);
    useEffect(() => {
        playerRef.current?.playFromBeginning();
    }, []);

    return (
        <>
            <Row className='justify-content-center'>
                <Col style={{ width: '40em' }}>
                    <Card style={{ display: 'ruby-text'}}>
                        <Card.Body className='p-4 text-center'>
                            <Player
                                icon={icError}
                                ref={playerRef} 
                                size={400}
                                onComplete={() => playerRef.current?.playFromBeginning()}
                            />
                            <div className='mt-4 pt-2'>
                                <h5>{t('Error')}</h5>
                                <p className='text-muted'>{message}</p>
                                <div className='mt-4'>
                                    <NavLink to={routes.DashboardProductionTracking} className='btn btn-primary'>
                                        <i className='mdi mdi-home me-1' />
                                        <span>{t('BackToHome')}</span>
                                    </NavLink>
                                </div>
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
            </Row>
        </>
    )
}

export default Error;

**Comment by baszczewski** [comment]
Our library is primarily designed to work with icons from the Lordicon service. As a general rule, we do not support animations from other sources. Can you confirm if this issue occurs with our icons as well?
