### ISSUE TITLE
Ability to change the colors of the icons

### ISSUE THREAD

**Issue by h-markus** [lordicondev/lordicon#8]
**Is your feature request related to a problem? Please describe.**
Currently, when changing the color of a Lottie icon, the color change applies globally to the entire icon. This limitation makes it difficult to customize icons with distinct primary and secondary colors, which is essential for creating visually appealing and consistent designs.

**Describe the solution you'd like**
I would like to have the ability to separately edit the primary and secondary colors of Lottie icons. This feature should allow users to define and apply different colors to distinct parts of the icon, providing greater flexibility and control over the appearance of the icons.

**Describe alternatives you've considered**
Currently, the only workaround is to manually edit the JSON files of the Lottie animations, which is not user-friendly and can be time-consuming, especially for users without technical expertise.

**Additional context**
Separating the color controls would greatly enhance the usability of Lottie animations in various applications, allowing for more sophisticated and customized designs. This feature would be particularly beneficial for designers and developers who need to maintain a consistent color scheme across their projects.

**Proposed Implementation:**

Introduce two new color properties: primaryColor and secondaryColor.
Allow users to define these colors in the animation settings.
Update the rendering engine to apply these colors to the appropriate parts of the icon.

For context, i am using React-Native

Thank you for considering this feature request. I believe it will be a valuable addition to the Lottie library, enhancing its flexibility and usability for a wide range of users.

**Comment by baszczewski** [comment]
Thank you very much for your feedback and suggestion. We have prepared a new version of the library that supports a dedicated "colors" parameter.
